# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5b3c57f7ce53f561d4d6b61a4d051a5fb94d3cde6ec9dd7a8c5a8df8ceaf307f0a0f93e4115dcf883261e86b4535bcfe77e2b9604d020b5c19ff172958903515

test:
  secret_key_base: b870d0804927d1fb4dc5dc93cde4b5a7b5b0b62ddabd7550077d199dcb27bb66835def7a6f5802b4744615779207d03d93de4e03191cbebfa56d4780fe251736

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
